# -*- coding: utf-8 -*-

LIFETIME = 86400  # seconds equal to one day
MAX_FINITE_ELEMENTS_NUMBER = 1500
DEFAULT_OUTPUT_STRESSES = [
    # {'name': 'sig_zz_n', 'description': 'Normal stress σzz,N resulting from the axial load N'},
    # {'name': 'sig_zz_mxx', 'description': 'Normal stress σzz,Mxx resulting from the bending moment Mxx'},
    # {'name': 'sig_zz_myy', 'description': 'Normal stress σzz,Myy resulting from the bending moment Myy'},
    # {'name': 'sig_zz_m11', 'description': 'Normal stress σzz,M11 resulting from the bending moment M11'},
    # {'name': 'sig_zz_m22', 'description': 'Normal stress σzz,M22 resulting from the bending moment M22'},
    # {'name': 'sig_zz_m', 'description': 'Normal stress σzz,ΣM resulting from all bending moments'},
    # {'name': 'sig_zx_mzz', 'description': 'x-component of the shear stress σzx,Mzz resulting from the torsion moment'},
    # {'name': 'sig_zy_mzz', 'description': 'y-component of the shear stress σzy,Mzz resulting from the torsion moment'},
    # {'name': 'sig_zxy_mzz', 'description': 'Resultant shear stress σzxy,Mzz resulting from the torsion moment'},
    # {'name': 'sig_zx_vx', 'description': 'x-component of the shear stress σzx,Vx resulting from the shear force Vx'},
    # {'name': 'sig_zy_vx', 'description': 'y-component of the shear stress σzy,Vx resulting from the shear force Vx'},
    # {'name': 'sig_zxy_vx', 'description': 'Resultant shear stress σzxy,Vx resulting from the shear force Vx'},
    # {'name': 'sig_zx_vy', 'description': 'x-component of the shear stress σzx,Vy resulting from the shear force Vy'},
    # {'name': 'sig_zy_vy', 'description': 'y-component of the shear stress σzy,Vy resulting from the shear force Vy'},
    # {'name': 'sig_zxy_vy', 'description': 'Resultant shear stress σzxy,Vy resulting from the shear force Vy'},
    # {'name': 'sig_zx_v', 'description': 'x-component of the shear stress σzx,ΣV resulting from all shear forces'},
    # {'name': 'sig_zy_v', 'description': 'y-component of the shear stress σzy,ΣV resulting from all shear forces'},
    # {'name': 'sig_zxy_v', 'description': 'Resultant shear stress σzxy,ΣV resulting from all shear forces'},
    {'name': 'sig_zz', 'description': 'Normal stress σzz'},
    # {'name': 'sig_zx', 'description': 'x-component of the shear stress σzx resulting from all actions'},
    # {'name': 'sig_zy', 'description': 'y-component of the shear stress σzy resulting from all actions'},
    {'name': 'sig_zxy', 'description': ' Resultant shear stress σzxy'},
    {'name': 'sig_vm', 'description': 'von Mises stress σvM'}
]

COMMON_STRUCTURAL_SECTIONS = [
    {'section_type': 'rect', 'image': 'web_layout/img/rect_geometry.png', 'name': 'Rectangular Section',
     'analyzed_section_base_name': 'rect_{d}_{b}_{mesh_sizes}', 'analyzing_function': 'analyze_rect',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth (y) of the rectangle'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width (x) of the rectangle'}]},

    {'section_type': 'circ', 'image': 'web_layout/img/circ_geometry.png', 'name': 'Circular Section',
    'analyzed_section_base_name': 'circ_{d}_{n}_{mesh_sizes}', 'analyzing_function': 'analyze_circ',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Diameter of the circle'},
                  {'name': 'n', 'step': '1', 'description': 'n (int) – Number of points discretising the circle'}]},
    {'section_type': 'chs', 'image': 'web_layout/img/chs_geometry.png',
     'name': 'Circular Hollow Section (CHS)',
     'analyzed_section_base_name': 'chs_{d}_{t}_{n}_{mesh_sizes}', 'analyzing_function': 'analyze_chs',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Outer diameter of the CHS'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the CHS'},
                  {'name': 'n', 'step': '1',
                   'description': 'n (int) – Number of points discretising the inner and outer circles'}]},
    {'section_type': 'elliptical', 'image': 'web_layout/img/elliptical_geometry.png',
     'name': 'Elliptical Section',
     'analyzed_section_base_name': 'elliptical_{d_y}_{d_x}_{n}_{mesh_sizes}', 'analyzing_function': 'analyze_elliptical',
     'elements': [{'name': 'd_y', 'step': 'any',
                   'description': 'd_y (float) – Diameter of the ellipse in the y-dimension'},
                  {'name': 'd_x', 'step': 'any',
                   'description': 'd_x (float) – Diameter of the ellipse in the x-dimension'},
                  {'name': 'n', 'step': '1', 'description': 'n (int) – Number of points discretising the ellipse'}]},
    {'section_type': 'ehs', 'image': 'web_layout/img/ehs_geometry.png',
     'name': 'Elliptical Hollow Section (EHS)',
     'analyzed_section_base_name': 'ehs_{d_y}_{d_x}_{t}_{n}_{mesh_sizes}', 'analyzing_function': 'analyze_ehs',
     'elements': [{'name': 'd_y', 'step': 'any',
                   'description': 'd_y (float) – Diameter of the ellipse in the y-dimension'},
                  {'name': 'd_x', 'step': 'any',
                   'description': 'd_x (float) – Diameter of the ellipse in the x-dimension'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the EHS'},
                  {'name': 'n', 'step': '1',
                   'description': 'n (int) – Number of points discretising the inner and outer ellipses'}]},
    {'section_type': 'rhs', 'image': 'web_layout/img/rhs_geometry.png',
     'name': 'Rectangular Hollow Section (RHS)',
     'analyzed_section_base_name': 'rhs_{d}_{b}_{t}_{r_out}_{n_r}_{mesh_sizes}', 'analyzing_function': 'analyze_rhs',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) - Depth of the RHS'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) - Width of the RHS'},
                  {'name': 't', 'step': 'any', 'description': 't (float) - Thickness of the RHS'},
                  {'name': 'r_out', 'step': 'any', 'description': 'r_out (float) - Outer radius of the RHS'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) - Number of points discretising the inner and outer radii'}]},
    {'section_type': 'i', 'image': 'web_layout/img/i_geometry.png', 'name': 'I-Section',
     'analyzed_section_base_name': 'i_{d}_{b}_{t_f}_{t_w}_{r}_{n_r}_{mesh_sizes}', 'analyzing_function': 'analyze_i',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the I-section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the I-section'},
                  {'name': 't_f', 'step': 'any', 'description': 't_f (float) – Flange thickness of the I-section'},
                  {'name': 't_w', 'step': 'any', 'description': 't_w (float) – Web thickness of the I-section'},
                  {'name': 'r', 'step': 'any', 'description': 'r (float) – Root radius of the I-section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the root radius'}]},
    {'section_type': 'monosymm_i', 'image': 'web_layout/img/monosymm_i_geometry.png',
     'name': 'Monosymmetric I-Section',
     'analyzed_section_base_name': 'monosymm_i_{d}_{b_t}_{b_b}_{t_ft}_{t_fb}_{t_w}_{r}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_monosymm_i',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the I-section'},
                  {'name': 'b_t', 'step': 'any', 'description': 'b_t (float) – Top flange width'},
                  {'name': 'b_b', 'step': 'any', 'description': 'b_b (float) – Bottom flange width'},
                  {'name': 't_ft', 'step': 'any',
                   'description': 't_ft (float) – Top flange thickness of the I-section'},
                  {'name': 't_fb', 'step': 'any',
                   'description': 't_fb (float) – Bottom flange thickness of the I-section'},
                  {'name': 't_w', 'step': 'any', 'description': 't_w (float) – Web thickness of the I-section'},
                  {'name': 'r', 'step': 'any', 'description': 'r (float) – Root radius of the I-section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the root radius'}]},
    {'section_type': 'tap_fl_i', 'image': 'web_layout/img/tap_fl_i_geometry.png',
     'name': 'Tapered Flange I-Section',
     'analyzed_section_base_name': 'tap_fl_i_{d}_{b}_{t_f}_{t_w}_{r_r}_{r_f}_{alpha}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_tap_fl_i',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the Tapered Flange I-section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the Tapered Flange I-section'},
                  {'name': 't_f', 'step': 'any',
                   'description': 't_f (float) – Mid-flange thickness of the Tapered Flange I-section'
                                  ' (measured at the point equidistant from the face of the web'
                                  ' to the edge of the flange)'},
                  {'name': 't_w', 'step': 'any',
                   'description': 't_w (float) – Web thickness of the Tapered Flange I-section'},
                  {'name': 'r_r', 'step': 'any',
                   'description': 'r_r (float) – Root radius of the Tapered Flange I-section'},
                  {'name': 'r_f', 'step': 'any',
                   'description': 'r_f (float) – Flange radius of the Tapered Flange I-section'},
                  {'name': 'alpha', 'step': 'any',
                   'description': 'alpha (float) – Flange angle of the Tapered Flange I-section (degrees)'},
                  {'name': 'n_r', 'step': '1', 'description': 'n_r (int) – Number of points'
                                                              ' discretising the radii'}]},
    {'section_type': 'pfc', 'image': 'web_layout/img/pfc_geometry.png',
     'name': 'Parallel Flange Channel (PFC) Section',
     'analyzed_section_base_name': 'pfc_{d}_{b}_{t_f}_{t_w}_{r}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_pfc',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the PFC section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the PFC section'},
                  {'name': 't_f', 'step': 'any', 'description': 't_f (float) – Flange thickness of the PFC section'},
                  {'name': 't_w', 'step': 'any', 'description': 't_w (float) – Web thickness of the PFC section'},
                  {'name': 'r', 'step': 'any', 'description': 'r (float) – Root radius of the PFC section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the root radius'}]},
    {'section_type': 'tap_fl_c', 'image': 'web_layout/img/tap_fl_c_geometry.png',
     'name': 'Tapered Flange Channel Section',
     'analyzed_section_base_name': 'tap_fl_c_{d}_{b}_{t_f}_{t_w}_{r_r}_{r_f}_{alpha}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_tap_fl_c',
     'elements': [{'name': 'd', 'step': 'any',
                   'description': 'd (float) – Depth of the Tapered Flange Channel section'},
                  {'name': 'b', 'step': 'any',
                   'description': 'b (float) – Width of the Tapered Flange Channel section'},
                  {'name': 't_f', 'step': 'any',
                   'description': 't_f (float) – Mid-flange thickness of the Tapered Flange Channel section '
                                  '(measured at the point equidistant from the face of the web'
                                  ' to the edge of flange)'},
                  {'name': 't_w', 'step': 'any',
                   'description': 't_w (float) – Web thickness of the Tapered Flange Channel section'},
                  {'name': 'r_r', 'step': 'any',
                   'description': 'r_r (float) – Root radius of the Tapered Flange Channel section'},
                  {'name': 'r_f', 'step': 'any',
                   'description': 'r_f (float) – Flange radius of the Tapered Flange Channel section'},
                  {'name': 'alpha', 'step': 'any',
                   'description': 'alpha (float) – Flange angle of the Tapered Flange Channel section (degrees)'},
                  {'name': 'n_r', 'step': '1', 'description': 'n_r (int) – Number of points'
                                                              ' discretising the radii'}]},
    {'section_type': 't', 'image': 'web_layout/img/t_geometry.png', 'name': 'Tee Section',
     'analyzed_section_base_name': 't_{d}_{b}_{t_f}_{t_w}_{r}_{n_r}_{mesh_sizes}', 'analyzing_function': 'analyze_t',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the Tee section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the Tee section'},
                  {'name': 't_f', 'step': 'any', 'description': 't_f (float) – Flange thickness of the Tee section'},
                  {'name': 't_w', 'step': 'any', 'description': 't_w (float) – Web thickness of the Tee section'},
                  {'name': 'r', 'step': 'any', 'description': 'r (float) – Root radius of the Tee section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the root radius'}]},
    {'section_type': 'angle', 'image': 'web_layout/img/angle_geometry.png', 'name': 'Angle Section',
     'analyzed_section_base_name': 'angle_{d}_{b}_{t}_{r_r}_{r_t}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_angle',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the angle section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the angle section'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the angle section'},
                  {'name': 'r_r', 'step': 'any', 'description': 'r_r (float) – Root radius of the angle section'},
                  {'name': 'r_t', 'step': 'any', 'description': 'r_t (float) – Toe radius of the angle section'},
                  {'name': 'n_r', 'step': '1', 'description': 'n_r (int) – Number of points'
                                                              ' discretising the radii'}]},
    {'section_type': 'cee', 'image': 'web_layout/img/cee_geometry.png', 'name': 'Cee Section',
     'analyzed_section_base_name': 'cee_{d}_{b}_{l}_{t}_{r_out}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_cee',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the Cee section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the Cee section'},
                  {'name': 'l', 'step': 'any', 'description': 'l (float) – Lip of the Cee section'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the Cee section'},
                  {'name': 'r_out', 'step': 'any', 'description': 'r_out (float) – Outer radius of the Cee section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the outer radius'}]},
    {'section_type': 'zed', 'image': 'web_layout/img/zed_geometry.png', 'name': 'Zed Section',
     'analyzed_section_base_name': 'zed_{d}_{b_l}_{b_r}_{l}_{t}_{r_out}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_zed',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the Zed section'},
                  {'name': 'b_l', 'step': 'any', 'description': 'b_l (float) – Left flange width of the Zed section'},
                  {'name': 'b_r', 'step': 'any',
                   'description': 'b_r (float) – Right flange width of the Zed section'},
                  {'name': 'l', 'step': 'any', 'description': 'l (float) – Lip of the Zed section'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the Zed section'},
                  {'name': 'r_out', 'step': 'any', 'description': 'r_out (float) – Outer radius of the Zed section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the outer radius'}]},
    {'section_type': 'cruciform', 'image': 'web_layout/img/cruciform_geometry.png', 'name': 'Cruciform Section',
     'analyzed_section_base_name': 'cruciform_{d}_{b}_{t}_{r}_{n_r}_{mesh_sizes}',
     'analyzing_function': 'analyze_cruciform',
     'elements': [{'name': 'd', 'step': 'any', 'description': 'd (float) – Depth of the cruciform section'},
                  {'name': 'b', 'step': 'any', 'description': 'b (float) – Width of the cruciform section'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the cruciform section'},
                  {'name': 'r', 'step': 'any', 'description': 'r (float) – Root radius of the cruciform section'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the root radius'}]},
    {'section_type': 'polygon', 'image': 'web_layout/img/polygon_geometry.png', 'name': 'Polygon Section',
     'analyzed_section_base_name': 'polygon_{d}_{t}_{r_in}_{n_r}_{rot}_{n_sides}_{mesh_sizes}',
     'analyzing_function': 'analyze_polygon',
     'elements': [{'name': 'd', 'step': 'any',
                   'description': 'd (float) – Pitch circle diameter of the outer bounding polygon'
                                  ' (i.e. diameter of circle that passes through all vertices of the outer polygon)'},
                  {'name': 't', 'step': 'any', 'description': 't (float) – Thickness of the polygon section wall'},
                  {'name': 'r_in', 'step': 'any',
                   'description': 'r_in (float) – Inner radius of the polygon corners. By default,'
                                  ' if not specified, a polygon with no corner radii is generated'},
                  {'name': 'n_r', 'step': '1',
                   'description': 'n_r (int) – Number of points discretising the inner and outer radii,'
                                  ' ignored if no inner radii is specified'},
                  {'name': 'rot', 'step': 'any',
                   'description': 'rot – Initial counterclockwise rotation in degrees. By default'
                                  ' bottom face is aligned with x axis'},
                  {'name': 'n_sides', 'step': '1', 'description': 'n_sides (int) – The number of the polygon sides'}]},
]
